version: '3.8'

services:
  # Servicio de Base de Datos (PostgreSQL)
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tienda_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret_password

  # Servicio de tu API Django
  web_django: # El Monolito (v1)
    build: .
    command: gunicorn Tienda.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_NAME=tienda_db
      - DB_USER=postgres
      - DB_PASSWORD=secret_password
      - DB_HOST=db
      - DB_PORT=5432

  pagos_flask: # El Microservicio (v2) - EL ESTRANGULADOR
    build: ./microservicio_pagos
    ports:
      - "5000:5000" # Solo para pruebas iniciales, luego lo cerraremos

  # Nginx - Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web_django
      - pagos_flask

# Definicion del volumen persistente
volumes:
  postgres_data:
